/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalbuild.SinglePlay;

import static finalbuild.Navigation.mainMenu;
import static finalbuild.SinglePlay.MechanicsH.DeclareWinOrDrawH;
import static finalbuild.SinglePlay.MechanicsH.DeclareWinOrDrawH;
import static finalbuild.SinglePlay.MechanicsH.checkDiagonalH;
import static finalbuild.SinglePlay.MechanicsH.checkHorizontalH;
import static finalbuild.SinglePlay.MechanicsH.checkVerticalH;
import static finalbuild.SinglePlay.MechanicsH.count;
import static finalbuild.SinglePlay.MechanicsH.letter;
import static finalbuild.SinglePlay.MechanicsH.whosTurn;

/**
 *
 * @author giovannikolo
 */
public class Hardboard extends javax.swing.JFrame {

    /**
     * Creates new form Hardboard
     */
    public Hardboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MiddleRightButtonH = new javax.swing.JButton();
        BottomLeftButtonH = new javax.swing.JButton();
        BottomMiddleButtonH = new javax.swing.JButton();
        BottomRightButtonH = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        UpperLeftButtonH = new javax.swing.JButton();
        UpperMiddleButtonH = new javax.swing.JButton();
        UpperRightButtonH = new javax.swing.JButton();
        MiddleLeftButtonH = new javax.swing.JButton();
        MiddleMiddleButtonH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        MiddleRightButtonH.setBackground(new java.awt.Color(255, 255, 255));
        MiddleRightButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleRightButtonHActionPerformed(evt);
            }
        });

        BottomLeftButtonH.setBackground(new java.awt.Color(255, 255, 255));
        BottomLeftButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomLeftButtonHActionPerformed(evt);
            }
        });

        BottomMiddleButtonH.setBackground(new java.awt.Color(255, 255, 255));
        BottomMiddleButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomMiddleButtonHActionPerformed(evt);
            }
        });

        BottomRightButtonH.setBackground(new java.awt.Color(255, 255, 255));
        BottomRightButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomRightButtonHActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setText("GIve up!!");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Main Menu");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        UpperLeftButtonH.setBackground(new java.awt.Color(255, 255, 255));
        UpperLeftButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperLeftButtonHActionPerformed(evt);
            }
        });

        UpperMiddleButtonH.setBackground(new java.awt.Color(255, 255, 255));
        UpperMiddleButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperMiddleButtonHActionPerformed(evt);
            }
        });

        UpperRightButtonH.setBackground(new java.awt.Color(255, 255, 255));
        UpperRightButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperRightButtonHActionPerformed(evt);
            }
        });

        MiddleLeftButtonH.setBackground(new java.awt.Color(255, 255, 255));
        MiddleLeftButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleLeftButtonHActionPerformed(evt);
            }
        });

        MiddleMiddleButtonH.setBackground(new java.awt.Color(255, 255, 255));
        MiddleMiddleButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleMiddleButtonHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpperLeftButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpperMiddleButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpperRightButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(MiddleLeftButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MiddleMiddleButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MiddleRightButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BottomLeftButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomMiddleButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomRightButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpperLeftButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpperMiddleButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpperRightButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MiddleLeftButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiddleMiddleButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiddleRightButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BottomLeftButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BottomMiddleButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BottomRightButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiddleRightButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleRightButtonHActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        MiddleRightButtonH.setText(letter);
        MiddleRightButtonH.setEnabled(false);
        checkHorizontalH();
        checkVerticalH();
        checkDiagonalH();
        DeclareWinOrDrawH();
    }//GEN-LAST:event_MiddleRightButtonHActionPerformed

    private void BottomLeftButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomLeftButtonHActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        BottomLeftButtonH.setText(letter);
        BottomLeftButtonH.setEnabled(false);
        checkHorizontalH();
        checkVerticalH();
        checkDiagonalH();
        DeclareWinOrDrawH();
    }//GEN-LAST:event_BottomLeftButtonHActionPerformed

    private void BottomMiddleButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomMiddleButtonHActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        BottomMiddleButtonH.setText(letter);
        BottomMiddleButtonH.setEnabled(false);
        checkHorizontalH();
        checkVerticalH();
        checkDiagonalH();
        DeclareWinOrDrawH();
    }//GEN-LAST:event_BottomMiddleButtonHActionPerformed

    private void BottomRightButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomRightButtonHActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        BottomRightButtonH.setText(letter);
        BottomRightButtonH.setEnabled(false);
        checkHorizontalH();
        checkVerticalH();
        checkDiagonalH();
        DeclareWinOrDrawH();
    }//GEN-LAST:event_BottomRightButtonHActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        DeclareWinOrDrawH();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void UpperLeftButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperLeftButtonHActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        UpperLeftButtonH.setText(letter);
        UpperLeftButtonH.setEnabled(false);
        checkHorizontalH();
        checkVerticalH();
        checkDiagonalH();
        DeclareWinOrDrawH();
    }//GEN-LAST:event_UpperLeftButtonHActionPerformed

    private void UpperMiddleButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperMiddleButtonHActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        UpperMiddleButtonH.setText(letter);
        UpperMiddleButtonH.setEnabled(false);
        checkHorizontalH();
        checkVerticalH();
        checkDiagonalH();
        DeclareWinOrDrawH();
    }//GEN-LAST:event_UpperMiddleButtonHActionPerformed

    private void UpperRightButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperRightButtonHActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        UpperRightButtonH.setText(letter);
        UpperRightButtonH.setEnabled(false);
        checkHorizontalH();
        checkVerticalH();
        checkDiagonalH();
        DeclareWinOrDrawH();
    }//GEN-LAST:event_UpperRightButtonHActionPerformed

    private void MiddleLeftButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleLeftButtonHActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        MiddleLeftButtonH.setText(letter);
        MiddleLeftButtonH.setEnabled(false);
        checkHorizontalH();
        checkVerticalH();
        checkDiagonalH();
        DeclareWinOrDrawH();
    }//GEN-LAST:event_MiddleLeftButtonHActionPerformed

    private void MiddleMiddleButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleMiddleButtonHActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        MiddleMiddleButtonH.setText(letter);
        MiddleMiddleButtonH.setEnabled(false);
        checkHorizontalH();
        checkVerticalH();
        checkDiagonalH();
        DeclareWinOrDrawH();
    }//GEN-LAST:event_MiddleMiddleButtonHActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        mainMenu(); 
          this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hardboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hardboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hardboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hardboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hardboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BottomLeftButtonH;
    public static javax.swing.JButton BottomMiddleButtonH;
    public static javax.swing.JButton BottomRightButtonH;
    public static javax.swing.JButton MiddleLeftButtonH;
    public static javax.swing.JButton MiddleMiddleButtonH;
    public static javax.swing.JButton MiddleRightButtonH;
    public static javax.swing.JButton UpperLeftButtonH;
    public static javax.swing.JButton UpperMiddleButtonH;
    public static javax.swing.JButton UpperRightButtonH;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    // End of variables declaration//GEN-END:variables
}
