/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalbuild.SinglePlay;


import static finalbuild.Navigation.mainMenu;
import static finalbuild.SinglePlay.MechanicsI.DeclareWinOrDrawI;
import static finalbuild.SinglePlay.MechanicsI.checkDiagonalI;
import static finalbuild.SinglePlay.MechanicsI.checkHorizontalI;
import static finalbuild.SinglePlay.MechanicsI.checkVerticalI;
import static finalbuild.SinglePlay.MechanicsI.letter;
import static finalbuild.SinglePlay.MechanicsI.count;
import static finalbuild.SinglePlay.MechanicsI.whosTurn;
/**
 *
 * @author giovannikolo
 */
public class Intermediateboard extends javax.swing.JFrame {

    /**
     * Creates new form Intermediate
     */
    public Intermediateboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MiddleRightButtonI = new javax.swing.JButton();
        BottomLeftButtonI = new javax.swing.JButton();
        BottomMiddleButtonI = new javax.swing.JButton();
        ButtomRIghtButtonI = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        UpperLeftButtonI = new javax.swing.JButton();
        UpperMiddleButtonI = new javax.swing.JButton();
        UpperRightButtonI = new javax.swing.JButton();
        MiddleLeftButtonI = new javax.swing.JButton();
        MiddleMiddleButtonI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        MiddleRightButtonI.setBackground(new java.awt.Color(255, 255, 255));
        MiddleRightButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleRightButtonIActionPerformed(evt);
            }
        });

        BottomLeftButtonI.setBackground(new java.awt.Color(255, 255, 255));
        BottomLeftButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomLeftButtonIActionPerformed(evt);
            }
        });

        BottomMiddleButtonI.setBackground(new java.awt.Color(255, 255, 255));
        BottomMiddleButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomMiddleButtonIActionPerformed(evt);
            }
        });

        ButtomRIghtButtonI.setBackground(new java.awt.Color(255, 255, 255));
        ButtomRIghtButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomRIghtButtonIActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setText("GIve up!!");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Main Menu");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        UpperLeftButtonI.setBackground(new java.awt.Color(255, 255, 255));
        UpperLeftButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperLeftButtonIActionPerformed(evt);
            }
        });

        UpperMiddleButtonI.setBackground(new java.awt.Color(255, 255, 255));
        UpperMiddleButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperMiddleButtonIActionPerformed(evt);
            }
        });

        UpperRightButtonI.setBackground(new java.awt.Color(255, 255, 255));
        UpperRightButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperRightButtonIActionPerformed(evt);
            }
        });

        MiddleLeftButtonI.setBackground(new java.awt.Color(255, 255, 255));
        MiddleLeftButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleLeftButtonIActionPerformed(evt);
            }
        });

        MiddleMiddleButtonI.setBackground(new java.awt.Color(255, 255, 255));
        MiddleMiddleButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleMiddleButtonIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpperLeftButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpperMiddleButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpperRightButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(MiddleLeftButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MiddleMiddleButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MiddleRightButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BottomLeftButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomMiddleButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtomRIghtButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpperLeftButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpperMiddleButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpperRightButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MiddleLeftButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiddleMiddleButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiddleRightButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BottomLeftButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BottomMiddleButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtomRIghtButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiddleRightButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleRightButtonIActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        MiddleRightButtonI.setText(letter);
        MiddleRightButtonI.setEnabled(false);
        checkHorizontalI();
        checkVerticalI();
        checkDiagonalI();
        DeclareWinOrDrawI();
    }//GEN-LAST:event_MiddleRightButtonIActionPerformed

    private void BottomLeftButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomLeftButtonIActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        BottomLeftButtonI.setText(letter);
        BottomLeftButtonI.setEnabled(false);
        checkHorizontalI();
        checkVerticalI();
        checkDiagonalI();
        DeclareWinOrDrawI();
    }//GEN-LAST:event_BottomLeftButtonIActionPerformed

    private void BottomMiddleButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomMiddleButtonIActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        BottomMiddleButtonI.setText(letter);
        BottomMiddleButtonI.setEnabled(false);
        checkHorizontalI();
        checkVerticalI();
        checkDiagonalI();
        DeclareWinOrDrawI();
    }//GEN-LAST:event_BottomMiddleButtonIActionPerformed

    private void ButtomRIghtButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomRIghtButtonIActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        ButtomRIghtButtonI.setText(letter);
        ButtomRIghtButtonI.setEnabled(false);
        checkHorizontalI();
        checkVerticalI();
        checkDiagonalI();
        DeclareWinOrDrawI();
    }//GEN-LAST:event_ButtomRIghtButtonIActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        DeclareWinOrDrawI();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void UpperLeftButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperLeftButtonIActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        UpperLeftButtonI.setText(letter);
        UpperLeftButtonI.setEnabled(false);
        checkHorizontalI();
        checkVerticalI();
        checkDiagonalI();
        DeclareWinOrDrawI();
    }//GEN-LAST:event_UpperLeftButtonIActionPerformed

    private void UpperMiddleButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperMiddleButtonIActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        UpperMiddleButtonI.setText(letter);
        UpperMiddleButtonI.setEnabled(false);
        checkHorizontalI();
        checkVerticalI();
        checkDiagonalI();
        DeclareWinOrDrawI();
    }//GEN-LAST:event_UpperMiddleButtonIActionPerformed

    private void UpperRightButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperRightButtonIActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        UpperRightButtonI.setText(letter);
        UpperRightButtonI.setEnabled(false);
        checkHorizontalI();
        checkVerticalI();
        checkDiagonalI();
        DeclareWinOrDrawI();
    }//GEN-LAST:event_UpperRightButtonIActionPerformed

    private void MiddleLeftButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleLeftButtonIActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        MiddleLeftButtonI.setText(letter);
        MiddleLeftButtonI.setEnabled(false);
        checkHorizontalI();
        checkVerticalI();
        checkDiagonalI();
        DeclareWinOrDrawI();
    }//GEN-LAST:event_MiddleLeftButtonIActionPerformed

    private void MiddleMiddleButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleMiddleButtonIActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        MiddleMiddleButtonI.setText(letter);
        MiddleMiddleButtonI.setEnabled(false);
        checkHorizontalI();
        checkVerticalI();
        checkDiagonalI();
        DeclareWinOrDrawI();
    }//GEN-LAST:event_MiddleMiddleButtonIActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        mainMenu(); 
          this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intermediateboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intermediateboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intermediateboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intermediateboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intermediateboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BottomLeftButtonI;
    public static javax.swing.JButton BottomMiddleButtonI;
    public static javax.swing.JButton ButtomRIghtButtonI;
    public static javax.swing.JButton MiddleLeftButtonI;
    public static javax.swing.JButton MiddleMiddleButtonI;
    public static javax.swing.JButton MiddleRightButtonI;
    public static javax.swing.JButton UpperLeftButtonI;
    public static javax.swing.JButton UpperMiddleButtonI;
    public static javax.swing.JButton UpperRightButtonI;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    // End of variables declaration//GEN-END:variables
}
