/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalbuild.Versus;

import static finalbuild.Navigation.mainMenu;
import static finalbuild.Versus.Mechanics.DeclareWinOrDraw;
import static finalbuild.Versus.Mechanics.checkDiagonal;
import static finalbuild.Versus.Mechanics.checkHorizontal;
import static finalbuild.Versus.Mechanics.checkVertical;
import static finalbuild.Versus.Mechanics.count;
import static finalbuild.Versus.Mechanics.letter;
import static finalbuild.Versus.Mechanics.updateBanner;
import static finalbuild.Versus.Mechanics.whosTurn;
import java.awt.Color;
/**
 *
 * @author giovannikolo
 */
public class versusboard extends javax.swing.JFrame {

    /**
     * Creates new form versusboard
     */
    public versusboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        UpperLeftButtonV = new javax.swing.JButton();
        UpperMiddleV = new javax.swing.JButton();
        UpperRightV = new javax.swing.JButton();
        MiddleLeftV = new javax.swing.JButton();
        MiddleMiddleButtonV = new javax.swing.JButton();
        MiddleRightButtonV = new javax.swing.JButton();
        BottomLeftButtonV = new javax.swing.JButton();
        ButtomMiddleButtonV = new javax.swing.JButton();
        BottomRightButtonV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Main Menu");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        UpperLeftButtonV.setBackground(new java.awt.Color(255, 255, 255));
        UpperLeftButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperLeftButtonVActionPerformed(evt);
            }
        });

        UpperMiddleV.setBackground(new java.awt.Color(255, 255, 255));
        UpperMiddleV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperMiddleVActionPerformed(evt);
            }
        });

        UpperRightV.setBackground(new java.awt.Color(255, 255, 255));
        UpperRightV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperRightVActionPerformed(evt);
            }
        });

        MiddleLeftV.setBackground(new java.awt.Color(255, 255, 255));
        MiddleLeftV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleLeftVActionPerformed(evt);
            }
        });

        MiddleMiddleButtonV.setBackground(new java.awt.Color(255, 255, 255));
        MiddleMiddleButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleMiddleButtonVActionPerformed(evt);
            }
        });

        MiddleRightButtonV.setBackground(new java.awt.Color(255, 255, 255));
        MiddleRightButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleRightButtonVActionPerformed(evt);
            }
        });

        BottomLeftButtonV.setBackground(new java.awt.Color(255, 255, 255));
        BottomLeftButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomLeftButtonVActionPerformed(evt);
            }
        });

        ButtomMiddleButtonV.setBackground(new java.awt.Color(255, 255, 255));
        ButtomMiddleButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomMiddleButtonVActionPerformed(evt);
            }
        });

        BottomRightButtonV.setBackground(new java.awt.Color(255, 255, 255));
        BottomRightButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomRightButtonVActionPerformed(evt);
            }
        });

        jLabel1.setText("h");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpperLeftButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpperMiddleV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpperRightV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MiddleLeftV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MiddleMiddleButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MiddleRightButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BottomLeftButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtomMiddleButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BottomRightButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpperLeftButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpperMiddleV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpperRightV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MiddleLeftV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MiddleMiddleButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MiddleRightButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BottomLeftButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtomMiddleButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BottomRightButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void jLabel1(java.awt.event.ActionEvent evt)
    {
        updateBanner();
    }
    
    private void UpperLeftButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperLeftButtonVActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        UpperLeftButtonV.setText(letter);
        UpperLeftButtonV.setEnabled(false);
        checkHorizontal();
        checkVertical();
        checkDiagonal();
        DeclareWinOrDraw();
    }//GEN-LAST:event_UpperLeftButtonVActionPerformed

    private void UpperMiddleVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperMiddleVActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        UpperMiddleV.setText(letter);
        UpperMiddleV.setEnabled(false);
        checkHorizontal();
        checkVertical();
        checkDiagonal();
        DeclareWinOrDraw();
    }//GEN-LAST:event_UpperMiddleVActionPerformed

    private void UpperRightVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperRightVActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        UpperRightV.setText(letter);
        UpperRightV.setEnabled(false);
        checkHorizontal();
        checkVertical();
        checkDiagonal();
        DeclareWinOrDraw();
    }//GEN-LAST:event_UpperRightVActionPerformed

    private void MiddleLeftVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleLeftVActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        MiddleLeftV.setText(letter);
        MiddleLeftV.setEnabled(false);
        checkHorizontal();
        checkVertical();
        checkDiagonal();
        DeclareWinOrDraw();
    }//GEN-LAST:event_MiddleLeftVActionPerformed

    private void MiddleMiddleButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleMiddleButtonVActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        MiddleMiddleButtonV.setText(letter);
        MiddleMiddleButtonV.setEnabled(false);
        checkHorizontal();
        checkVertical();
        checkDiagonal();
        DeclareWinOrDraw();

    }//GEN-LAST:event_MiddleMiddleButtonVActionPerformed

    private void MiddleRightButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleRightButtonVActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        MiddleRightButtonV.setText(letter);
        MiddleRightButtonV.setEnabled(false);
        checkHorizontal();
        checkVertical();
        checkDiagonal();
        DeclareWinOrDraw();
    }//GEN-LAST:event_MiddleRightButtonVActionPerformed

    private void BottomLeftButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomLeftButtonVActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        BottomLeftButtonV.setText(letter);
        BottomLeftButtonV.setEnabled(false);
        checkHorizontal();
        checkVertical();
        checkDiagonal();
        DeclareWinOrDraw();
    }//GEN-LAST:event_BottomLeftButtonVActionPerformed

    private void ButtomMiddleButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomMiddleButtonVActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        ButtomMiddleButtonV.setText(letter);
        ButtomMiddleButtonV.setEnabled(false);
        checkHorizontal();
        checkVertical();
        checkDiagonal();
        DeclareWinOrDraw();
    }//GEN-LAST:event_ButtomMiddleButtonVActionPerformed

    private void BottomRightButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomRightButtonVActionPerformed
        // TODO add your handling code here:
        count++;
        whosTurn();
        BottomRightButtonV.setText(letter);
        BottomRightButtonV.setEnabled(false);
        checkHorizontal();
        checkVertical();
        checkDiagonal();
        DeclareWinOrDraw();
    }//GEN-LAST:event_BottomRightButtonVActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        mainMenu(); 
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(versusboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(versusboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(versusboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(versusboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new versusboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BottomLeftButtonV;
    public static javax.swing.JButton BottomRightButtonV;
    public static javax.swing.JButton ButtomMiddleButtonV;
    public static javax.swing.JButton MiddleLeftV;
    public static javax.swing.JButton MiddleMiddleButtonV;
    public static javax.swing.JButton MiddleRightButtonV;
    public static javax.swing.JButton UpperLeftButtonV;
    public static javax.swing.JButton UpperMiddleV;
    public static javax.swing.JButton UpperRightV;
    private javax.swing.JButton jButton11;
    public static javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
